// Generated by CoffeeScript 1.4.0
/*
    jquery.module.js

    Copyright 2012, Acatl Pacheco
    Licensed under the MIT License.
*/(function(){(function(e,t){var n,r,i,s,o;s="module";o=!1;i=function(e){var n,r,i,s;i=e.split(".");n=t;s=void 0;r=void 0;r=0;s=i.length;o&&console.log("module: "+e);while(r<s&&n!==null){n=n[i[r]]=n[i[r]]||null;r++}return n};r=function(e,t,n){var r,s,o;if(!t)return;typeof t=="string"&&(t=t.replace(/\s/g,"").split(","));jQuery.isArray(t)||(t=[t]);o=[];while(t.length!==0){s=t.shift();r=typeof s=="string"?i(s):s;try{o.push(r(e,n))}catch(u){o.push(console.log("module error on: ["+s+"]",u))}}return o};n=function(t,n){this.element=e(t);this.options=n;this._name=s;this.init();return this};n.prototype.init=function(){return this.add(this.element.data("module-class"),this.options)};n.prototype.add=function(e,t){return r(this.element,e,t)};return e.fn[s]=function(t,r){var i;i=arguments;o=r;return this.each(function(){var r;r=e.data(this,"plugin_"+s);if(!r)return e.data(this,"plugin_"+s,new n(this,t));if(r[t])return r[t].apply(r,Array.prototype.slice.call(i,1))})}})(jQuery,window)}).call(this);