// Generated by CoffeeScript 1.3.3
/*
    jquery.module.js

    Copyright 2012, Acatl Pacheco
    Licensed under the MIT License.
*/(function(){(function(e,t){var n,r,i;i="module";r=function(e){var n,r,i,s;i=e.split(".");n=t;s=void 0;r=void 0;r=0;s=i.length;while(r<s&&n!==null){n=n[i[r]]=n[i[r]]||null;r++}return n};n=function(t,n){this.element=e(t);this.options=n;this._name=i;this.init();return this};n.prototype.init=function(){var e,t,n,i,s,o;e=this.element;n=e.data("module-class");if(n){t=n.replace(/\s/g,"").split(",");o=[];while(t.length!==0){i=t.shift();s=r(i);try{o.push(s(e,this.options))}catch(u){o.push(console.log("module error on: ["+i+"]",u))}}return o}};return e.fn[i]=function(t){var r;r=arguments;return this.each(function(){var s;s=e.data(this,"plugin_"+i);if(!s)return e.data(this,"plugin_"+i,new n(this,t));if(s[t])return s[t].apply(s,Array.prototype.slice.call(r,1))})}})(jQuery,window)}).call(this);