// Generated by CoffeeScript 1.3.3
/*
    jquery.tile.js

    Copyright 2012, Acatl Pacheco
    Licensed under the MIT License.
*/(function(){(function(e,t){var n,r,i,s;s="tile";r={};i=function(e){var n,r,i,s;i=e.split(".");n=t;s=void 0;r=void 0;r=0;s=i.length;while(r<s&&n!==null){n=n[i[r]]=n[i[r]]||null;r++}return n};n=function(t,n){this.element=e(t);this.options=e.extend({},r,n);this._defaults=r;this._name=s;this.init();return this};n.prototype.init=function(){var e,t,n;e=this.element;n=e.data("tile-class");if(n){t=i(n);try{return t(e)}catch(r){return console.log("Tile error on: ["+n+"]",r)}}};return e.fn[s]=function(t){var r;r=arguments;return this.each(function(){var i;i=e.data(this,"plugin_"+s);if(!i)return e.data(this,"plugin_"+s,new n(this,t));if(i[t])return i[t].apply(i,Array.prototype.slice.call(r,1))})}})(jQuery,window)}).call(this);